services:
  backend:
    image: wsd:latest
    build:
      context: ./wsd
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - internal
      - external
    volumes:
      - user_uploads:/wsd/mediafiles
    restart: unless-stopped

  frontend:
    build:
      context: ./wsd-frontend
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        NEXT_PUBLIC_WSD__DEBUG: ${NEXT_PUBLIC_WSD__DEBUG}
        NEXT_PUBLIC_WSD__NAME: ${NEXT_PUBLIC_WSD__NAME}
        NEXT_PUBLIC_WSD__MOTTO: ${NEXT_PUBLIC_WSD__MOTTO}
        NEXT_PUBLIC_WSD__DOMAIN: ${NEXT_PUBLIC_WSD__DOMAIN}
        NEXT_PUBLIC_WSD__API__BASE_URL: ${NEXT_PUBLIC_WSD__API__BASE_URL}
        NEXT_PUBLIC_WSD__API__AUTH_BASE_URL: ${NEXT_PUBLIC_WSD__API__AUTH_BASE_URL}
        NEXT_PUBLIC_WSD__LANGUAGE: ${NEXT_PUBLIC_WSD__LANGUAGE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__DSN: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__DSN}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__TRACES_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__TRACES_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_SESSION_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_SESSION_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_ON_ERROR_SAMPLE_RATE: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__SENTRY__REPLAYS_ON_ERROR_SAMPLE_RATE}
        NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__GOOGLE_ANALYTICS__GA_ID: ${NEXT_PUBLIC_WSD__FRONT_END__DEVTOOLS__GOOGLE_ANALYTICS__GA_ID}
        NEXT_PUBLIC_WSD__VERIFICATION__MICROSOFT__ASSOCIATED_APPLICATION_ID: ${NEXT_PUBLIC_WSD__VERIFICATION__MICROSOFT__ASSOCIATED_APPLICATION_ID}
        NEXT_PUBLIC_WSD__GITHUB_LINK: ${NEXT_PUBLIC_WSD__GITHUB_LINK}
    env_file: .env
    networks:
      - internal
      - external
    restart: unless-stopped

  server:
    build:
      context: ./wsd-server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${WSD_SERVER_PORT}:80"
    depends_on:
      - backend
      - frontend
    networks:
      internal:
      external:
        aliases:
          - "${WSD_SERVER_NETWORK_APEX_DOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_API_SUBDOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_AUTH_SUBDOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_ADMIN_SUBDOMAIN_ALIAS}"
    restart: unless-stopped

  database:
    build:
      context: ./wsd-database
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_DB: ${WSD__DB__NAME}
      POSTGRES_USER: ${WSD__DB__USER}
      POSTGRES_PASSWORD: ${WSD__DB__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3
    env_file: .env
    ports:
      - "5672:5672"
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    image: wsd:latest
    command: celery -A wsd worker --pool=threads --concurrency=10  # threads option is important for tensorflow
    env_file: .env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - internal
    restart: unless-stopped

  celery-beat:
    image: wsd:latest
    command: celery -A wsd beat
    env_file: .env
    depends_on:
      - backend
      - rabbitmq
    networks:
      - internal
    restart: unless-stopped

volumes:
  postgres_data:
  user_uploads:

networks:
  internal:
    internal: true
  external:
    driver: bridge
