include:
  - services/docker-compose.base.yml
  - services/docker-compose.backend.yml
  - services/docker-compose.database.yml

services:
  server:
    build:
      context: ../wsd-server
      dockerfile: ../wsd-server/Dockerfile
    env_file: ../.env
    ports:
      - "${WSD_SERVER_PORT}:80"
    networks:
      internal:
      external:
        aliases:
          - "${WSD_SERVER_NETWORK_APEX_DOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_API_SUBDOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_AUTH_SUBDOMAIN_ALIAS}"
          - "${WSD_SERVER_NETWORK_ADMIN_SUBDOMAIN_ALIAS}"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      backend:
        condition: service_started
    environment:
      WSD__HOSTS__FRONTEND_DOMAIN: "host.docker.internal"
      WSD__HOSTS__BACKEND_DOMAIN: "backend"
